### ISSUE TITLE
Использование библиотеки

### ISSUE THREAD

**Issue by khataev** [andrepolischuk/cbr-rates-cli#1]
Привет! Не против, что по-русски? )

Я новичек в JS, и я делаю простую страничку, на которой мне нужно получить курсы валют ЦБ на дату. Могу ли я как-то задействовать эту библиотеку или cbr-rates (кстати, не до конца понял в чем их отличие). У меня есть подозрение, что она заточена под node.js, а я его не использую, у меня страничка без серверной части и из пакетных менеджеров пока только bower. Также я заметил, что библиотека написана на новом синтаксисе JS - ES6 - не будет ли она конфликтовать с библиотеками, которые я использую, написанными на предыдущей версии? 
Хочу подключить твою библиотеку как-то так:
<script src="bower_components/moment/min/moment.min.js"></script>

Очень буду рад, если поможешь разобраться!

**Comment by andrepolischuk** [comment]
Привет, без серверной части не получится использовать, потому что `cbr-rates` только для node.js. А `cbr-rates-cli` для использования в коммандной строке.

**Comment by khataev** [comment]
Благодарю за разъяснение
